server {
  listen       80;
  server_name  _;

  root   /usr/share/nginx/html;
  index  index.html;

  # Serve static files directly
  location / {
    try_files $uri /index.html;
  }

  # Cache static assets
  location ~* \.(?:css|js|jpg|jpeg|gif|png|svg|ico|webp)$ {
    expires 30d;
    access_log off;
    add_header Cache-Control "public, max-age=2592000, immutable";
  }
}

